### ISSUE TITLE
make_map.launch fails in odom_tf-1

### ISSUE THREAD

**Issue by ocularb0b** [xaxxontech/oculusprime_ros#3]
On ubuntu 14.04 amd64, with ROS Indigo.
When running 'roslaunch oculusprime make_map.launch' I see the following:
Traceback (most recent call last):
  File "/home/scott/catkin_ws/src/oculusprime_ros/src/odom_tf.py", line 93, in <module>
    s = oculusprimesocket.replyBufferSearch("<state> distanceangle ")
  File "/home/scott/catkin_ws/src/oculusprime_ros/src/oculusprimesocket.py", line 73, in replyBufferSearch
    servermsg = (sockfileIO.readline()).strip()
AttributeError: 'NoneType' object has no attribute 'readline'
[odom_tf-1] process has died [pid 7594, exit code 1, cmd /home/scott/catkin_ws/src/oculusprime_ros/src/odom_tf.py __name:=odom_tf __log:=/home/scott/.ros/log/b943b7ee-afc6-11e4-a721-4851b77c02e5/odom_tf-1.log].
log file: /home/scott/.ros/log/b943b7ee-afc6-11e4-a721-4851b77c02e5/odom_tf-1*.log

Nothing helpful in odom_tf-1.log

**Comment by xaxxontech** [comment]
OculusPrime java must be up and running with the telnet server listening on port 4444 (disabled by default, enabled by changing the [telnetport line](http://www.xaxxon.com/documentation/view/oculus-prime-configuration-file#telnetport) in oculus_settings.txt:
`telnetport disabled`
to
`telnetport 4444`

([Updated ros docs](http://wiki.ros.org/oculusprime_ros#Enable_Java_Server_Telnet_Port) to reflect telnetport requirement)
